// Real Xapiand field-type keywords (192, lengths 2..23), from schema.cc.
// Shared by the keyword-set benchmark and any contender that needs a macro list.
#define FIELD_TYPES(X) \
  X("undefined") \
  X("object") \
  X("boolean") \
  X("date") \
  X("datetime") \
  X("float") \
  X("floating") \
  X("geo") \
  X("integer") \
  X("positive") \
  X("script") \
  X("term") \
  X("keyword") \
  X("string") \
  X("text") \
  X("time") \
  X("timedelta") \
  X("uuid") \
  X("array") \
  X("array/object") \
  X("object/array") \
  X("array/boolean") \
  X("boolean/array") \
  X("array/date") \
  X("date/array") \
  X("array/datetime") \
  X("datetime/array") \
  X("array/float") \
  X("float/array") \
  X("array/floating") \
  X("floating/array") \
  X("array/geo") \
  X("geo/array") \
  X("array/integer") \
  X("integer/array") \
  X("array/positive") \
  X("positive/array") \
  X("array/script") \
  X("script/array") \
  X("array/term") \
  X("term/array") \
  X("array/keyword") \
  X("keyword/array") \
  X("array/string") \
  X("string/array") \
  X("array/text") \
  X("text/array") \
  X("array/time") \
  X("time/array") \
  X("array/timedelta") \
  X("timedelta/array") \
  X("array/uuid") \
  X("uuid/array") \
  X("foreign") \
  X("foreign/object") \
  X("object/foreign") \
  X("foreign/boolean") \
  X("boolean/foreign") \
  X("foreign/date") \
  X("date/foreign") \
  X("foreign/datetime") \
  X("datetime/foreign") \
  X("foreign/float") \
  X("float/foreign") \
  X("foreign/floating") \
  X("floating/foreign") \
  X("foreign/geo") \
  X("geo/foreign") \
  X("foreign/integer") \
  X("integer/foreign") \
  X("foreign/positive") \
  X("positive/foreign") \
  X("foreign/script") \
  X("script/foreign") \
  X("foreign/term") \
  X("term/foreign") \
  X("foreign/keyword") \
  X("keyword/foreign") \
  X("foreign/string") \
  X("string/foreign") \
  X("foreign/text") \
  X("text/foreign") \
  X("foreign/time") \
  X("time/foreign") \
  X("foreign/timedelta") \
  X("timedelta/foreign") \
  X("foreign/uuid") \
  X("uuid/foreign") \
  X("foreign/array") \
  X("array/foreign") \
  X("foreign/array/object") \
  X("foreign/object/array") \
  X("array/foreign/object") \
  X("array/object/foreign") \
  X("object/foreign/array") \
  X("object/array/foreign") \
  X("foreign/array/boolean") \
  X("foreign/boolean/array") \
  X("array/foreign/boolean") \
  X("array/boolean/foreign") \
  X("boolean/foreign/array") \
  X("boolean/array/foreign") \
  X("foreign/array/date") \
  X("foreign/date/array") \
  X("array/foreign/date") \
  X("array/date/foreign") \
  X("date/foreign/array") \
  X("date/array/foreign") \
  X("foreign/array/datetime") \
  X("foreign/datetime/array") \
  X("array/foreign/datetime") \
  X("array/datetime/foreign") \
  X("datetime/foreign/array") \
  X("datetime/array/foreign") \
  X("foreign/array/float") \
  X("foreign/float/array") \
  X("array/foreign/float") \
  X("array/float/foreign") \
  X("float/foreign/array") \
  X("float/array/foreign") \
  X("foreign/array/floating") \
  X("foreign/floating/array") \
  X("array/foreign/floating") \
  X("array/floating/foreign") \
  X("floating/foreign/array") \
  X("floating/array/foreign") \
  X("foreign/array/geo") \
  X("foreign/geo/array") \
  X("array/foreign/geo") \
  X("array/geo/foreign") \
  X("geo/foreign/array") \
  X("geo/array/foreign") \
  X("foreign/array/integer") \
  X("foreign/integer/array") \
  X("array/foreign/integer") \
  X("array/integer/foreign") \
  X("integer/foreign/array") \
  X("integer/array/foreign") \
  X("foreign/array/positive") \
  X("foreign/positive/array") \
  X("array/foreign/positive") \
  X("array/positive/foreign") \
  X("positive/foreign/array") \
  X("positive/array/foreign") \
  X("foreign/array/script") \
  X("foreign/script/array") \
  X("array/foreign/script") \
  X("array/script/foreign") \
  X("script/foreign/array") \
  X("script/array/foreign") \
  X("foreign/array/term") \
  X("foreign/term/array") \
  X("array/foreign/term") \
  X("array/term/foreign") \
  X("term/foreign/array") \
  X("term/array/foreign") \
  X("foreign/array/keyword") \
  X("foreign/keyword/array") \
  X("array/foreign/keyword") \
  X("array/keyword/foreign") \
  X("keyword/foreign/array") \
  X("keyword/array/foreign") \
  X("foreign/array/string") \
  X("foreign/string/array") \
  X("array/foreign/string") \
  X("array/string/foreign") \
  X("string/foreign/array") \
  X("string/array/foreign") \
  X("foreign/array/text") \
  X("foreign/text/array") \
  X("array/foreign/text") \
  X("array/text/foreign") \
  X("text/foreign/array") \
  X("text/array/foreign") \
  X("foreign/array/time") \
  X("foreign/time/array") \
  X("array/foreign/time") \
  X("array/time/foreign") \
  X("time/foreign/array") \
  X("time/array/foreign") \
  X("foreign/array/timedelta") \
  X("foreign/timedelta/array") \
  X("array/foreign/timedelta") \
  X("array/timedelta/foreign") \
  X("timedelta/foreign/array") \
  X("timedelta/array/foreign") \
  X("foreign/array/uuid") \
  X("foreign/uuid/array") \
  X("array/foreign/uuid") \
  X("array/uuid/foreign") \
  X("uuid/foreign/array") \
  X("uuid/array/foreign")
